name: Deploy to s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRETKEY }}

    - name: Copy files to S3
      run: |
        aws s3 sync . s3://${{ secrets.BUCKETNAME }} --delete --exclude ".git/*" --exclude ".github/*" --exclude "README.md"
